#!/bin/sh

[ -t 0 ] || exec > $0.log 2>&1

cat > $0_$$.awk << !
BEGIN {
    system("rm $0_$$.awk")
    PIDFILE = "/run/" gensub("^.*/([^/]+)$", "\\\1", "g", "$0") "d.pid"
    print "-" PROCINFO["pgrpid"] > PIDFILE; close(PIDFILE)

    while (1) {

        #
        # configure this as needed
        #
        CMD = "/root/bin/CableLoadMonitor -d 1 -i -w 1500 -h 200 2>&1"
        print "CMD: <" CMD ">"
        while (CMD | getline line > 0) {
            print line 
            fflush("")
        }
        close(CMD)
        CMD = "sleep 5"; CMD | getline line; close(CMD)
    }
}
!
exec awk -f $0_$$.awk

