#!/bin/sh

echo start in bg:
echo feh -d --reload .5 CableLoadMonitor.png

display_data()
{
Width=1500 # results in 1581x1111
Height=800

BACK=100
BACK=300
BACK=500
BACK=700
BACK=1000
BACK=2000
#BACK=3600
#BACK=16000
#BACK=30000
#BACK=86400

Date=`date`
rrdtool graph CableLoadMonitor_.png -a PNG --lower-limit 0 \
--title="Graph generated at $Date" -w $Width -h $Height --end now --start end-${BACK}s \
'DEF:f01=CableLoadMonitor.rrd:f01:AVERAGE' \
'DEF:f02=CableLoadMonitor.rrd:f02:AVERAGE' \
'DEF:f03=CableLoadMonitor.rrd:f03:AVERAGE' \
'DEF:f04=CableLoadMonitor.rrd:f04:AVERAGE' \
'DEF:f05=CableLoadMonitor.rrd:f05:AVERAGE' \
'DEF:f06=CableLoadMonitor.rrd:f06:AVERAGE' \
'DEF:f07=CableLoadMonitor.rrd:f07:AVERAGE' \
'DEF:f08=CableLoadMonitor.rrd:f08:AVERAGE' \
'DEF:f09=CableLoadMonitor.rrd:f09:AVERAGE' \
'DEF:f10=CableLoadMonitor.rrd:f10:AVERAGE' \
'DEF:f11=CableLoadMonitor.rrd:f11:AVERAGE' \
'DEF:f12=CableLoadMonitor.rrd:f12:AVERAGE' \
'DEF:f13=CableLoadMonitor.rrd:f13:AVERAGE' \
'DEF:f14=CableLoadMonitor.rrd:f14:AVERAGE' \
'DEF:f15=CableLoadMonitor.rrd:f15:AVERAGE' \
'DEF:f16=CableLoadMonitor.rrd:f16:AVERAGE' \
'DEF:sum=CableLoadMonitor.rrd:sum:AVERAGE' \
\
'LINE:f01#ff00ff:530' \
'LINE:f02#ff00e0:538' \
'LINE:f03#ff00c0:546' \
'LINE:f04#ff00a0:554' \
'LINE:f05#ff0080:562' \
'LINE:f06#ff0060:570' \
'LINE:f07#ff0040:578' \
'LINE:f08#ff0020:586' \
'LINE:f09#00ffff:594' \
'LINE:f10#00e0ff:602' \
'LINE:f11#00c0ff:610' \
'LINE:f12#00a0ff:618' \
'LINE:f13#0080ff:626' \
'LINE:f14#0060ff:634' \
'LINE:f15#0040ff:642' \
'LINE:f16#0020ff:650' \
\
'LINE:sum#00ff00:sum\l' \
\
"GPRINT:f01:LAST:530 last\: %6.0lf %s" \
"GPRINT:f01:AVERAGE:avg\: %6.0lf %s" \
"GPRINT:f01:MIN:min\: %6.0lf %s" \
"GPRINT:f01:MAX:max\: %6.0lf %s\j" \
"GPRINT:f02:LAST:538 last\: %6.0lf %s" \
"GPRINT:f02:AVERAGE:avg\: %6.0lf %s" \
"GPRINT:f02:MIN:min\: %6.0lf %s" \
"GPRINT:f02:MAX:max\: %6.0lf %s\j" \
"GPRINT:f03:LAST:546 last\: %6.0lf %s" \
"GPRINT:f03:AVERAGE:avg\: %6.0lf %s" \
"GPRINT:f03:MIN:min\: %6.0lf %s" \
"GPRINT:f03:MAX:max\: %6.0lf %s\j" \
"GPRINT:f04:LAST:554 last\: %6.0lf %s" \
"GPRINT:f04:AVERAGE:avg\: %6.0lf %s" \
"GPRINT:f04:MIN:min\: %6.0lf %s" \
"GPRINT:f04:MAX:max\: %6.0lf %s\j" \
"GPRINT:f05:LAST:562 last\: %6.0lf %s" \
"GPRINT:f05:AVERAGE:avg\: %6.0lf %s" \
"GPRINT:f05:MIN:min\: %6.0lf %s" \
"GPRINT:f05:MAX:max\: %6.0lf %s\j" \
"GPRINT:f06:LAST:570 last\: %6.0lf %s" \
"GPRINT:f06:AVERAGE:avg\: %6.0lf %s" \
"GPRINT:f06:MIN:min\: %6.0lf %s" \
"GPRINT:f06:MAX:max\: %6.0lf %s\j" \
"GPRINT:f07:LAST:578 last\: %6.0lf %s" \
"GPRINT:f07:AVERAGE:avg\: %6.0lf %s" \
"GPRINT:f07:MIN:min\: %6.0lf %s" \
"GPRINT:f07:MAX:max\: %6.0lf %s\j" \
"GPRINT:f08:LAST:586 last\: %6.0lf %s" \
"GPRINT:f08:AVERAGE:avg\: %6.0lf %s" \
"GPRINT:f08:MIN:min\: %6.0lf %s" \
"GPRINT:f08:MAX:max\: %6.0lf %s\j" \
"GPRINT:f09:LAST:594 last\: %6.0lf %s" \
"GPRINT:f09:AVERAGE:avg\: %6.0lf %s" \
"GPRINT:f09:MIN:min\: %6.0lf %s" \
"GPRINT:f09:MAX:max\: %6.0lf %s\j" \
"GPRINT:f10:LAST:602 last\: %6.0lf %s" \
"GPRINT:f10:AVERAGE:avg\: %6.0lf %s" \
"GPRINT:f10:MIN:min\: %6.0lf %s" \
"GPRINT:f10:MAX:max\: %6.0lf %s\j" \
"GPRINT:f11:LAST:610 last\: %6.0lf %s" \
"GPRINT:f11:AVERAGE:avg\: %6.0lf %s" \
"GPRINT:f11:MIN:min\: %6.0lf %s" \
"GPRINT:f11:MAX:max\: %6.0lf %s\j" \
"GPRINT:f12:LAST:618 last\: %6.0lf %s" \
"GPRINT:f12:AVERAGE:avg\: %6.0lf %s" \
"GPRINT:f12:MIN:min\: %6.0lf %s" \
"GPRINT:f12:MAX:max\: %6.0lf %s\j" \
"GPRINT:f13:LAST:626 last\: %6.0lf %s" \
"GPRINT:f13:AVERAGE:avg\: %6.0lf %s" \
"GPRINT:f13:MIN:min\: %6.0lf %s" \
"GPRINT:f13:MAX:max\: %6.0lf %s\j" \
"GPRINT:f14:LAST:634 last\: %6.0lf %s" \
"GPRINT:f14:AVERAGE:avg\: %6.0lf %s" \
"GPRINT:f14:MIN:min\: %6.0lf %s" \
"GPRINT:f14:MAX:max\: %6.0lf %s\j" \
"GPRINT:f15:LAST:642 last\: %6.0lf %s" \
"GPRINT:f15:AVERAGE:avg\: %6.0lf %s" \
"GPRINT:f15:MIN:min\: %6.0lf %s" \
"GPRINT:f15:MAX:max\: %6.0lf %s\j" \
"GPRINT:f16:LAST:650 last\: %6.0lf %s" \
"GPRINT:f16:AVERAGE:avg\: %6.0lf %s" \
"GPRINT:f16:MIN:min\: %6.0lf %s" \
"GPRINT:f16:MAX:max\: %6.0lf %s\j" \
"GPRINT:sum:LAST:sum last\: %6.0lf %s" \
"GPRINT:sum:AVERAGE:avg\: %6.0lf %s" \
"GPRINT:sum:MIN:min\: %6.0lf %s" \
"GPRINT:sum:MAX:max\: %6.0lf %s\j"
}

while :
do
display_data
# mv the file to avoid partial load by display tool
mv CableLoadMonitor_.png CableLoadMonitor.png
sleep 1
done

